### ISSUE TITLE
IE11: sedaScatterplot is undefined

### ISSUE THREAD

**Issue by amygroshek** [Hyperobjekt/react-seda-scatterplot#17]
This is technically flagging code in the seda-site repo, but seen some research suggesting that it can be related to react modules or to babel, so I'm documenting here as well. 

Scatterplot.js throws an error in IE11, right at the createElement call, finding sedaScatterplot undefined. plot.js subsequently throws a related error pertaining to the scatterplot object provided to it... 

<img width="732" alt="Screen Shot 2019-09-25 at 1 09 14 PM" src="https://user-images.githubusercontent.com/746182/65627873-e06ef500-df95-11e9-8dff-84ff522d24b9.png">

I've run into issues like this before with IE11 and I resolved a previous error with this technique of running Object.assign() on the props, but I can't seem to find a workaround for this. (Also, the search component goes through createElement just fine, similar code, in plot.js.)

<img width="751" alt="Screen Shot 2019-09-25 at 1 09 08 PM" src="https://user-images.githubusercontent.com/746182/65627953-10b69380-df96-11e9-90a3-e3ba73691c3d.png">

**Comment by Lane** [comment]
@amygroshek okay to close this or are there still issues?

**Comment by amygroshek** [comment]
Yes, sorry @Lane , thought I had closed this.
